language: java

#env:
#  DOCKER_COMPOSE_VERSION: 1.8.0

sudo: required

services:
  - docker

dist: trusty

before_install:
  # Docker Compose Install
  - sudo apt-get update
  - docker-compose --version
  - cp .travis.settings.xml $HOME/.m2/settings.xml

install:
  - mvn clean install
  - mvn package

before_script:
  # Disable services enabled by default
  - sudo service mysql stop
  - sudo service postgresql stop

script:
  - docker-compose up -d

after_success:
#  - curl http://0.0.0.0:8080/Richkware-Manager-Server/test

after_script:
  - docker-compose stop
